---
# Unseal Vault secrets
- name: Unseal Vault
  hosts: localhost

  tasks:
    - name: Unseal Vault using environment-provided keys
      ansible.builtin.include_role:
        name: openbao
      vars:
        action: unseal
        # Prefer setting via environment variables:
        #  VAULT_ADDR: e.g. https://<ip>:8200
        #  VAULT_UNSEAL_KEYS_JSON: JSON array of unseal keys, e.g. ["key1","key2","key3"]
        vault_address: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR', default=Undefined) }}"
        vault_unseal_keys: "{{ lookup('ansible.builtin.env', 'VAULT_UNSEAL_KEYS', default='[]') | from_json }}"
      no_log: true
